-- Generated by SQL Maestro for MySQL. Release date 22-12-2012
-- 04-04-2013 16:47:09
-- ----------------------------------
-- Alias: portugolbd at localhost
-- Database name: portugolbd
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.6.10
-- Session ID: 22
-- Character set: utf8
-- Collation: utf8_general_ci


DROP DATABASE IF EXISTS portugolbd;

CREATE DATABASE portugolbd
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

USE portugolbd;

/* Tables */
DROP TABLE IF EXISTS capitulo;

CREATE TABLE capitulo (
  Id         int(10) AUTO_INCREMENT NOT NULL,
  Nome       varchar(255),
  Descricao  varchar(255),
  PRIMARY KEY (Id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS perguntas;

CREATE TABLE perguntas (
  id           int AUTO_INCREMENT NOT NULL,
  pergunta     varchar(300) NOT NULL,
  dificuldade  int(5) NOT NULL,
  linguagem    varchar(20) NOT NULL DEFAULT 'portugues',
  capitulo     int NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS respostas;

CREATE TABLE respostas (
  TesteId      int(10) NOT NULL,
  PerguntasId  int(10) NOT NULL,
  Nota         int(2),
  Resposta     varchar(255),
  PRIMARY KEY (TesteId, PerguntasId)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS solucao;

CREATE TABLE solucao (
  Id           int(10) AUTO_INCREMENT NOT NULL,
  Entradas     varchar(255),
  Saidas       varchar(255),
  PerguntasId  int(10) NOT NULL,
  PRIMARY KEY (Id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS teste;

CREATE TABLE teste (
  Id              int(10) AUTO_INCREMENT NOT NULL,
  Descricao       int(10),
  UtilizadoresId  int(10) NOT NULL,
  Duracao         time,
  PRIMARY KEY (Id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS utilizadores;

CREATE TABLE utilizadores (
  Id        int(10) AUTO_INCREMENT NOT NULL,
  Nome      varchar(255) NOT NULL,
  Morada    varchar(255) NOT NULL,
  Contacto  int(10) NOT NULL,
  Email     varchar(255) NOT NULL,
  PRIMARY KEY (Id)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX capitulo
  ON perguntas
  (capitulo);

CREATE INDEX FKRespostas531118
  ON respostas
  (PerguntasId);

CREATE INDEX FKRespostas935132
  ON respostas
  (TesteId);

CREATE INDEX FKSolucao53423
  ON solucao
  (PerguntasId);

CREATE INDEX FKTeste452546
  ON teste
  (UtilizadoresId);

/* Foreign Keys */
ALTER TABLE perguntas
  ADD CONSTRAINT capitulo
  FOREIGN KEY (capitulo)
    REFERENCES capitulo(Id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE respostas
  ADD CONSTRAINT FKRespostas531118
  FOREIGN KEY (PerguntasId)
    REFERENCES perguntas(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE respostas
  ADD CONSTRAINT FKRespostas935132
  FOREIGN KEY (TesteId)
    REFERENCES teste(Id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE solucao
  ADD CONSTRAINT FKSolucao53423
  FOREIGN KEY (PerguntasId)
    REFERENCES perguntas(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE teste
  ADD CONSTRAINT FKTeste452546
  FOREIGN KEY (UtilizadoresId)
    REFERENCES utilizadores(Id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

/* Data for table "capitulo" */


/* Data for table "perguntas" */


/* Data for table "respostas" */


/* Data for table "solucao" */


/* Data for table "teste" */


/* Data for table "utilizadores" */
